FROM noaaepic/ubuntu22.04-intel-unified:v1.6.0-fms202401

# Build WM
WORKDIR /opt

RUN git clone --recursive -b develop https://github.com/ufs-community/ufs-weather-model.git

RUN mkdir -p /work && \
    mkdir -p /work2 && \
    mkdir -p /contrib && \
    mkdir -p /lustre  && \
    mkdir -p /scratch1 && \
    mkdir -p /scratch2 && \
    mkdir -p /glade && \
    mkdir -p /data && \
    mkdir -p /scratch && \
    mkdir -p /lfs && \
    mkdir -p /u && \
    mkdir -p /discover && \
    mkdir -p /mnt && \
    mkdir -p /lfs1 && \
    mkdir -p /lfs2 && \
    mkdir -p /lfs3 && \
    mkdir -p /lfs4 && \
    mkdir -p /export && \
    mkdir -p /Users && \
    mkdir -p /ncrc && \
    mkdir -p /opt/ufs-weather-model/container-scripts  && \
    mkdir -p /opt/ufs-weather-model/bin
COPY stage-rt.sh /opt
WORKDIR /opt/ufs-weather-model/tests-dev
COPY fv3_slurm.IN_singularity test_cases/exp_conf
COPY compile_slurm.IN_singularity test_cases/exp_conf
COPY machine_singularity.config machine_config
COPY baseline_setup.yaml .
RUN chmod a+rx test_cases/exp_conf/fv3_slurm.IN_singularity test_cases/exp_conf/compile_slurm.IN_singularity && \
    chmod a+rx machine_config/machine_singularity.config baseline_setup.yaml
#WORKDIR /opt/ufs-weather-model/bin
#RUN rm -f * && ln -s ../build_container_executable.sh make && ln -s ../build_container_executable.sh cmake
WORKDIR /opt/ufs-weather-model/container-scripts
COPY run_container_executable.sh .
COPY build_container_executable.sh .
RUN chmod a+rx /opt/stage-rt.sh run_container_executable.sh build_container_executable.sh
RUN source /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/.bashenv-fms && \
     #grep pathJoin modulefiles/ufs_common.lua | awk -F "\"" '{print "module load "$2}' > mods && \
     #source ./mods && module list && \
     module load jasper zlib libpng hdf5 netcdf-c netcdf-fortran parallelio esmf fms bacio && \
     module load crtm g2 g2tmpl ip sp w3emc gftl-shared mapl scotch py-pyyaml ecbuild && \ 
     export PATH=/opt/intel/oneapi/compiler/2024.0/bin:SINGULARITY_WORKING_DIR/ufs-weather-model/tests-dev:$PATH && \
     echo FI_PROVIDER_PATH=$FI_PROVIDER_PATH > ufswm.env && \
     echo PATH=$PATH >> ufswm.env && \
     echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> ufswm.env && \
     echo LIBRARY_PATH=$LIBRARY_PATH >> ufswm.env && \
     echo CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH >> ufswm.env && \
     echo MODULEPATH=$MODULEPATH >> ufswm.env && \
     echo CC=`which icc` >> ufswm.env && \
     echo FC=`which ifort` >> ufswm.env && \
     echo CXX=`which icpc` >> ufswm.env && \
     echo I_MPI_ROOT=$I_MPI_ROOT >> ufswm.env && \
     echo ESMFMKFILE=$ESMFMKFILE >> ufswm.env && \
     echo PYTHONPATH=$PYTHONPATH >> ufswm.env
