From noaaepic/ubuntu22.04-hpckit:2023.1.0
#From intel/ubuntu22.04-hpckit:2023.1.0
ARG branch_name

#ENV branch=$branch_name
ENV branch=1.5.1
RUN mkdir -p /opt/build
RUN apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     ca-certificates curl &&   rm -rf /var/lib/apt/lists/*
# install cmake
RUN cd /opt/build &&     curl -LO https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1-linux-x86_64.sh && /bin/bash cmake-3.23.1-linux-x86_64.sh --prefix=/usr/local --skip-license

# update apt
RUN apt-get update -yq --allow-unauthenticated

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
# Install some basics that will be needed by all apps
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
apt install -y --no-install-recommends  vim && \ 
apt install -y --no-install-recommends  wget && \
apt install -y --no-install-recommends  libexpat1-dev&& \
apt install -y --no-install-recommends  bc && \
apt install -y --no-install-recommends  time && \
apt install -y --no-install-recommends  libtiff-dev && \
apt install -y --no-install-recommends  bison && \
apt install -y --no-install-recommends  flex && \
apt install -y --no-install-recommends  libbz2-dev && \
apt install -y --no-install-recommends  apt-utils && \
apt install -y --no-install-recommends  tcl-dev && \
apt install -y --no-install-recommends  rsync && \
apt install -y --no-install-recommends  texinfo && \
apt install -y --no-install-recommends  libbz2-dev && \
apt install -y --no-install-recommends  awscli && \

#RUN apt install -y --no-install-recommends  environment-modules && \
apt install -y --no-install-recommends  build-essential && \
apt install -y --no-install-recommends  m4 && \
apt install -y --no-install-recommends  git && \
apt install -y --no-install-recommends  git-lfs && \
apt install -y --no-install-recommends  bzip2 && \
apt install -y --no-install-recommends  unzip && \
apt install -y --no-install-recommends  automake && \
apt install -y --no-install-recommends  autoconf && \
apt install -y --no-install-recommends  xterm && \
apt install -y --no-install-recommends  libcurl4-openssl-dev && \
apt install -y --no-install-recommends  libssl-dev && \
apt install -y --no-install-recommends  meson && \
apt install -y --no-install-recommends  mysql-server && \
apt install -y --no-install-recommends  libmysqlclient-dev && \
apt install -y --no-install-recommends  file && \
apt install -y --no-install-recommends  python3-dev python3-pip && \
rm -rf /var/lib/apt/lists/* 

ENV PATH="${PATH}:/usr/local:/opt/intel/oneapi/compiler/2023.2.3/linux/bin/intel64"

RUN echo "dash dash/sh boolean false" | debconf-set-selections && \
# the dash shell breaks everything. Replace it with bash as default /bin/sh
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash && \
# some packages can't find libpython in x86_64, so link them in /usr/lib
    ln -s /usr/lib/x86_64-linux-gnu/libpython3.10.a /usr/lib && ln -s /usr/lib/x86_64-linux-gnu/libpython3.10.so /usr/lib && \
    cd opt && \
# Install lua and lmod from source
    wget https://sourceforge.net/projects/lmod/files/lua-5.1.4.9.tar.bz2 && tar xvfj lua-5.1.4.9.tar.bz2 && \
    cd lua-5.1.4.9 && ./configure --prefix=/usr && make -j 4 && make install && git clone --recursive https://github.com/TACC/Lmod.git && \
    cd Lmod && ./configure --prefix=/usr && make -j 4 && make install && \  
# spack scipy install is broken, so install on the system
    pip install scipy && pip install cython && \
# install boost from source
    cd /opt && wget https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.gz && \
    tar xvfz boost_1_78_0.tar.gz && cd boost_1_78_0 && ./bootstrap.sh --prefix=/usr/ --with-python=/usr/bin/python3 && ./b2 install && \
# without an actual python executable, env python fails, so link python3 to python
    ln -s /usr/bin/python3 /usr/bin/python && \
# remove build artifacts to reduce size
    cd .. && rm -rf boost* && \
    rm -rf /opt/build /opt/spack-stack/spack-stack-$branch/cache/* && \
    rm -rf /opt/lua* Lmod

# Prepare spack-stack just like it is built on RDHPCS platforms under the spack-stack umbrella
RUN mkdir -p /opt/spack-stack
WORKDIR /opt/spack-stack

#Copy in the ubuntu-intel configuration files
ADD ubuntu-intel-21.3-1.5.1.tar.gz /opt/spack-stack
## Either copy in the spack-mirror or pull it from s3
#ADD spack-mirror-1.6.0.tar.gz /opt
RUN mkdir -p /opt/spack-mirror
##RUN wget https://epic-sandbox-srw.s3.amazonaws.com/spack-mirror.tar.gz && tar xvfz spack-mirror.tar.gz && rm spack-mirror.tar.gz

# This clone version will change for each successive release
RUN git clone -b release/$branch --recursive https://github.com/jcsda/spack-stack.git spack-stack-$branch && \
#RUN git clone -b update-srw-template --recursive https://github.com/EdwardSnyder-NOAA/spack-stack.git spack-stack-$branch && \
    cd /opt/spack-stack/spack-stack-$branch && \
# set the spack directories to be safe for use by git even though they are in /opt
    git config --global --add safe.directory /opt/spack-stack/spack-stack-$branch && \
    git config --global --add safe.directory /opt/spack-stack/spack-stack-$branch/spack && \

# Get any recent updates to the release
    git remote update && git checkout release/$branch && git pull origin release/$branch && \
    git submodule sync && git submodule update  && \
    mv /opt/spack-stack/ubuntu-intel configs/sites && \ 
# Modify ufs-srw-dev template
    sed -i '11,20d' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|hdf5@1.14.0||g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|esmf@8.4.2|esmf@8.5.0|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|fms@2023.01|fms@2023.02.01|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|bufr@12.0.0||g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|ip@3.3.3|ip@4.3.0|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|gftl-shared@1.5.0|gftl-shared@1.6.1|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|mapl@2.35.2|mapl@2.40.3|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|yafyaml@1.1.0||g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|w3emc@2.9.2|w3emc@2.10.0|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|wgrib2@2.0.8|wgrib2@3.1.1|g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|ncio@1.1.2||g' configs/templates/ufs-srw-dev/spack.yaml && \
    sed -i 's|gsi-ncdiag@1.1.2||g' configs/templates/ufs-srw-dev/spack.yaml && \

# Create the environment
    . ./setup.sh && spack compiler rm gcc@11.4.0 && \
    export SPACK_SYSTEM_CONFIG_PATH="$PWD/env/ufs-srw-env/site" && spack stack create env --site ubuntu-intel --template ufs-srw-dev --name ufs-srw-env && \
    spack compiler add oneapi && spack compiler list && \
    sed -i 's/\=2021/2021/g' /root/.spack/linux/compilers.yaml && \

# Concretize 
    . ./setup.sh && spack env activate envs/ufs-srw-env && \ 
    unset SPACK_SYSTEM_CONFIG_PATH && \ 
    spack config add "packages:fontconfig:variants:+pic" && \
    spack config add "packages:pixman:variants:+pic" && \
    spack config add "packages:cairo:variants:+pic" && \
    spack concretize  && mkdir /usr/bin/info && \
    spack mirror add unified file:/opt/spack-mirror && spack install --no-check-signature --no-checksum |& tee install.log && \
    rm -rf /opt/dist /opt/build /opt/spack-stack/spack-stack-$branch/cache/* /opt/spack-mirror && \
# refresh the modulefiles and create meta-modules
    source /usr/lmod/lmod/init/bash && \
    sed -i '/intel-oneapi-mpi/d' envs/ufs-srw-env/common/modules.yaml && \
    mv /root/.spack /root/.spack.old && \
    spack module lmod refresh -y && \
    spack stack setup-meta-modules && \
    module use /opt/spack-stack/spack-stack-$branch/envs/ufs-srw-env/install/modulefiles/Core && \
    module avail && \
    echo "source /usr/lmod/lmod/init/bash" >> /root/.bashenv && \
    echo "module use /opt/spack-stack/spack-stack-$branch/envs/ufs-srw-env/install/modulefiles/Core" >> /root/.bashenv && \
    echo "module load stack-intel intel-oneapi-mpi" >> /root/.bashenv && \
    echo "module load stack-intel-oneapi-mpi" >> /root/.bashenv && \
    #echo "module load ufs-weather-model-env" >> /root/.bashenv && \
    echo "[[ -s ~/.bashenv ]] && source ~/.bashenv" >> /root/.bash_profile && \
    echo "[[ -s ~/.bashenv ]] && source ~/.bashenv" >> /root/.bashrc && \
    cp ~/.bashenv /opt/spack-stack/spack-stack-$branch 
RUN source /root/.bashenv && module list && \
    module load jasper/2.0.32 netcdf-fortran/4.6.0 bacio/2.4.1 ip/4.3.0 sigio/2.3.2 wgrib2/3.1.1 zlib/1.2.13 && \
    module load crtm/2.4.0 sp/2.3.3 mapl w3nco/2.4.1 libpng/1.6.37 esmf g2/3.4.5 libjpeg/2.1.0 fms/2023.02.01 && \
    module load w3emc/2.10.0 nemsio/2.5.4 netcdf-c/4.9.2 g2tmpl/1.10.2 gftl-shared sfcio/1.4.1 parallelio/2.5.10 wrf-io/1.2.0 &&\
    echo "ENV PATH=$PATH" > srw.envs && \
    echo "ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> srw.envs && \
    echo "ENV LIBRARY_PATH=$LIBRARY_PATH" >> srw.envs && \
    echo "ENV MODULEPATH=$MODULEPATH" >> srw.envs && \
    echo "ENV FI_PROVIDER_PATH=$FI_PROVIDER_PATH" >> srw.envs && \
    echo "ENV CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" >> srw.envs && \
    echo ENV CC=`which mpiicc` >> srw.envs && \
    echo ENV FC=`which mpiifort` >> srw.envs && \
    echo ENV CXX=`which mpiicpc` >> srw.envs && \
    echo "DONE" 
COPY stage-container.sh /opt
COPY sing-bin.tar.gz /opt
ENV SHELL=/bin/bash
