FROM noaaepic/ubuntu22.04-intel-unified:v1.6.0

WORKDIR /opt/spack-stack/spack-stack-1.6.0 

# Create the fms-2024.01 env
RUN . ./setup.sh && \ 
    #spack compiler rm gcc@11.4.0 && \
    export SPACK_SYSTEM_CONFIG_PATH="/opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/site" && \
    spack stack create env --name fms-2024.01 --template empty --site ubuntu-intel --upstream /opt/spack-stack/spack-stack-1.6.0/envs/unified-env/install && \
   # spack compiler add oneapi && spack compiler list && \
   # sed -i 's/\=2021/2021/g' /root/.spack/linux/compilers.yaml && \
    sed -i '20 i \    version("2024.01", sha256="29ac23a5a2a4765ae66d218bb261cb04f7ad44618205ab0924c4e66c9ef8fa38")' spack/var/spack/repos/builtin/packages/fms/package.py && \
    sed -i '28 i \    version("3.5.1", sha256="a9acdb5d23eca532838f21c4a917727ac85851fc9e1f100d65a6f27c1a563998")' spack/var/spack/repos/builtin/packages/g2/package.py && \
    sed -i '24 i \    version("1.13.0", sha256="7e52cccc91277bcedbd9e13ee3478480e744eb22d13c5b636bd0ad91bf43d38e")' spack/var/spack/repos/builtin/packages/g2tmpl/package.py && \
    sed -i '34 i \    depends_on("g2c@1.7:", when="^g2@3.5:")' spack/var/spack/repos/builtin/packages/grib-util/package.py && \
    cd /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01 && \
    spack env activate . && \
    spack add upp-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1 && \
    spack add ip %intel && \
    spack add nco@5.0.6 %intel && \
    spack add met@11.1.0 %intel && \
    spack add metplus@5.1.0 %intel && \
    spack add fms@2024.01 %intel && \
    spack add prod-util@2.1.1 %intel && \
    spack add wgrib2@2.0.8 %intel && \
    spack add grib-util@1.3.0 %intel ^g2@3.5.1 && \
    spack add ufs-weather-model-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1 && \
#
# Concretize
    spack concretize 2>&1 | tee log.concretize-fms202401 && \
    spack install 2>&1 | tee log.install-fms202401 && \
#
# Refresh modulefiles and create meta-modules
    source /usr/lmod/lmod/init/bash && \
    sed -i '/intel-oneapi-mpi/d' /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/common/modules.yaml && \ 
    spack module lmod refresh -y --upstream-modules && \
    spack stack setup-meta-modules && \
    module use /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core && \
    module avail && \
    echo "source /usr/lmod/lmod/init/bash" >> .bashenv-fms && \
    echo "module use /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core" >> .bashenv-fms && \
    echo "module load stack-intel intel-oneapi-mpi" >> .bashenv-fms && \
    echo "module load stack-intel-oneapi-mpi" >> .bashenv-fms && \
    echo "DONE2" 
#
ENV SHELL=/bin/bash
