FROM noaaepic/ubuntu20.04-base-intel:release-v1.3.0
WORKDIR /opt/spack-stack/spack-stack-1.3.0

RUN git config --global --add safe.directory /opt/spack-stack/spack-stack-1.3.0
RUN git config --global --add safe.directory /opt/spack-stack/spack-stack-1.3.0/spack
RUN git remote update && git checkout release/1.3.0 && git pull origin release/1.3.0
RUN git submodule sync && git submodule update 
#RUN wget https://epic-sandbox-srw.s3.amazonaws.com/spack-mirror.tar.gz && tar xvfz spack-mirror.tar.gz && rm spack-mirror.tar.gz
RUN apt update && apt -y install libcurl4-openssl-dev texinfo libmysqlclient-dev freetype2-demos libbz2-dev
RUN source ./setup.sh && \
    sed -i s/"'%apple-clang', '%gcc', //g"  configs/templates/unified-dev/spack.yaml && \
    mkdir -p /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel && \
    cp /root/.spack/linux/compilers.yaml /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel && ls -l /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel && \
    find /opt/spack-stack/spack-stack-1.3.0/spack/opt/spack/ -iname intel-oneapi-mpi* && \
    loc=`find /opt/spack-stack/spack-stack-1.3.0/spack/opt/spack/ -iname intel-oneapi-mpi* | head -n 1` && \
    mpiver=`spack find intel-oneapi-mpi | grep intel-oneapi-mpi | awk -F "@" '{print $2}'` && \
    compver=`spack find intel-oneapi-compilers | grep intel-oneapi-compilers | awk -F "@" '{print $2}'` && \
    echo "config:" > /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/config.yaml && \
    echo "  build_jobs: 8" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/config.yaml && \
    echo "modules:" > /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/modules.yaml && \
    echo "  default:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/modules.yaml && \
    echo "    enable::" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/modules.yaml && \
    echo "    - lmod" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/modules.yaml && \
    echo "packages:" > /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "  all:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    compiler:: [intel@$compver]" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    providers:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "      mpi:: [intel-oneapi-mpi@$mpiver]" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    target: [core2]" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "  mpi:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    buildable: False" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "  intel-oneapi-mpi:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    externals:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "    - spec: intel-oneapi-mpi@$mpiver" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "      modules:" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "      - impi/$mpiver" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml && \
    echo "      prefix: $loc" >> /opt/spack-stack/spack-stack-1.3.0/configs/sites/ubuntu-intel/packages.yaml
RUN echo "add line" && sed -i 's/cmake\/3.22.1//g' /root/.bashenv 
RUN . ./setup.sh && spack compiler rm gcc@9.4.0 && spack external find --all && spack stack create env --site ubuntu-intel --template unified-dev --name unified-dev && \
    cat envs/unified-dev/site/compilers.yaml | head -n 14 > comp.yaml && cp comp.yaml envs/unified-dev/site/compilers.yaml && \
    sed -i 's/2023.0.0/2021.8.0/g' envs/unified-dev/site/packages.yaml && \
    spack env activate envs/unified-dev && \ 
    spack concretize  && mkdir /usr/bin/info && \
    echo "done"
COPY unified.pub /opt/spack-stack/spack-stack-1.3.0
COPY unified.private /opt/spack-stack/spack-stack-1.3.0
ADD env-files.tar.gz /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev
#ADD spack-mirror-ue.tar.gz /opt
RUN cd /opt && wget https://epic-sandbox-srw.s3.amazonaws.com/spack-mirror-ue.tar.gz && tar xvfz spack-mirror-ue.tar.gz && rm spack-mirror-ue.tar.gz
RUN ls -l /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev && source ./setup.sh && spack env activate envs/unified-dev && \
     spack mirror add unified file:/opt/spack-mirror && spack gpg trust unified.pub && spack gpg trust unified.private && \
     spack install  --no-check-signature --no-checksum |& tee install.log 
ENV SHELL=/bin/bash
RUN . ./setup.sh && source /usr/share/lmod/lmod/init/bash && \
    mpiver=`spack find intel-oneapi-mpi | grep intel-oneapi-mpi | awk -F "@" '{print $2}'` && \
    compver=`spack find intel-oneapi-compilers | grep intel-oneapi-compilers | awk -F "@" '{print $2}'` && \
    echo $mpiver && echo $compver && \
    spack env activate envs/unified-dev && \ 
    ln -s /usr/bin/python3 /usr/bin/python && \
    sed -i 's/2023.0.0/2021.8.0/g' envs/unified-dev/site/packages.yaml && \
    spack stack setup-meta-modules && \
    spack module lmod refresh -y && \
    module use /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles/Core && \
    module avail && \
    ls -l /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles/Core && \
    sed -i 's/impi/intel-oneapi-mpi/g' /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles/intel/*/stack-intel-oneapi-mpi/*.lua && \
    find /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles -iname "*.lua" | xargs grep -l depends_on | xargs sed -i 's/depends_on/-- depends_on/g' && \
    echo "module use /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles/Core" >> /root/.bashenv && \
    echo "module load stack-intel stack-intel-oneapi-mpi" >> /root/.bashenv && \
    source /root/.bashenv && \
    echo "[[ -s ~/.bashenv ]] && source ~/.bashenv" >> /root/.bash_profile && \
    echo "[[ -s ~/.bashenv ]] && source ~/.bashenv" >> /root/.bashrc && \
    cp ~/.bashenv /opt/spack-stack/spack-stack-1.3.0 && \
    echo "DONE2" 
WORKDIR /opt/spack-stack/spack-stack-1.3.0
RUN source ./setup.sh && spack env activate envs/unified-dev && \
    head -n 5 ./.bashenv > bashenv && mv ./bashenv ./.bashenv && source ./.bashenv && \
    spack module lmod refresh -y && sed -i 's/,/ /g' .bashenv && \
    find /opt/spack-stack/spack-stack-1.3.0/envs/unified-dev/install/modulefiles -iname "*.lua" | xargs grep -l depends_on | xargs sed -i 's/depends_on/-- depends_on/g' 
RUN source /root/.bashenv && module list && \
    module load ecbuild/3.6.5 fckit/0.10.0 gsl-lite/0.37.0 jasper/2.0.32 jedi-fv3-env/unified-dev atlas/0.32.1 && \
    module load libjpeg/2.1.0 pkg-config/0.29.2 curl/7.68.0 zstd/1.5.2 esmf/8.3.0b09 fms/2022.04 bacio/2.4.1 crtm-fix/2.4.0_emc && \
    module load git-lfs/2.9.2 crtm/2.4.0 g2/3.4.5 g2tmpl/1.10.2 ip/3.3.3 sp/2.3.3 w3emc/2.9.2 gftl/1.8.1 gftl-shared/1.5.0 && \
    module load yafyaml/0.5.1 mapl/2.22.0-esmf-8.3.0b09 netcdf-c netcdf-fortran parallelio && \
    module load zlib libpng hdf5 && \
    export PATH=$PATH:/opt/jedi-bundle/build/bin:/opt/land-DA_workflow/singularity/bin && \
    export LD_LIBRARY_PATH=/opt/land-DA_workflow/build/lib:$LD_LIBRARY_PATH && \
    echo "ENV PATH=$PATH" > landda.envs && \
    echo "ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> landda.envs && \
    echo "ENV LIBRARY_PATH=$LIBRARY_PATH" >> landda.envs && \
    echo "ENV MODULEPATH=$MODULEPATH" >> landda.envs && \
    echo "ENV FI_PROVIDER_PATH=$FI_PROVIDER_PATH" >> landda.envs && \
    echo "ENV CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" >> landda.envs && \
    echo ENV CC=`which mpiicc` >> landda.envs && \
    echo ENV FC=`which mpiifort` >> landda.envs && \
    echo ENV CXX=`which mpiicpc` >> landda.envs && \
    module purge && source /root/.bashenv && \
    module load jasper/2.0.32 netcdf-fortran/4.6.0 bacio/2.4.1 ip/3.3.3 yafyaml/0.5.1 sigio/2.3.2 wgrib2/2.0.8 zlib/1.2.13 openblas/0.3.19 && \
    module load parallelio/2.5.9 crtm/2.4.0 sp/2.3.3 mapl/2.22.0-esmf-8.3.0b09 w3nco/2.4.1 libpng/1.6.37 esmf/8.3.0b09 g2/3.4.5 libjpeg/2.1.0 && \
    module load w3emc/2.9.2 nemsio/2.5.2 wrf-io/1.2.0 netcdf-c/4.9.2 bufr/11.7.1 g2tmpl/1.10.2 gftl-shared/1.5.0 sfcio/1.4.1 ncio/1.1.2 &&\
    echo "ENV PATH=$PATH" > srw.envs && \
    echo "ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> srw.envs && \
    echo "ENV LIBRARY_PATH=$LIBRARY_PATH" >> srw.envs && \
    echo "ENV MODULEPATH=$MODULEPATH" >> srw.envs && \
    echo "ENV FI_PROVIDER_PATH=$FI_PROVIDER_PATH" >> srw.envs && \
    echo "ENV CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" >> srw.envs && \
    echo ENV CC=`which mpiicc` >> srw.envs && \
    echo ENV FC=`which mpiifort` >> srw.envs && \
    echo ENV CXX=`which mpiicpc` >> srw.envs && \
    cp ~/.bashenv /opt/spack-stack/spack-stack-1.3.0 && \
    rm -rf /opt/spack-mirror
RUN rm -rf /opt/dist /opt/build /opt/spack-stack/spack-stack-1.3.0/cache/*
