FROM noaaepic/ubuntu22.04-intel-unified:v1.6.0

WORKDIR /opt/spack-stack/spack-stack-1.6.0 

# Create the fms-2024.01 env
RUN . ./setup.sh && \
    spack stack create env --name fms-2024.01 --template empty --site ubuntu-intel --upstream /opt/spack-stack/spack-stack-1.6.0/envs/unified-env/install && \
    cd /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01 && \
    spack env activate . && \
    spack add upp-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1 && \
    spack add ip %intel && \
    spack add prod-util@2.1.1 %intel && \
    spack add wgrib2@2.0.8 %intel && \
    spack add grib-util@1.3.0 %intel ^g2@3.5.1 && \
    spack add ufs-weather-model-env %intel ^g2tmpl@1.13.0 ^g2@3.5.1 && \
    spack add nco@5.0.6 %intel && \
    spack add met@11.1.0 %intel && \
    spack add metplus@5.1.0 %intel && \
    spack add fms@2024.01 %intel && \
#
# Concretize
    spack concretize 2>&1 | tee log.concretize-fms202401 && \
    spack install 2>&1 | tee log.install-fms202401 && \
#
# Refresh modulefiles and create meta-modules
    spack module lmod refresh --upstream-modules && \
    spack stack setup-meta-modules && \
    module use /opt/spack-stack/spack-stack-1.6.0/envs/fms-2024.01/install/modulefiles/Core && \
    module avail && \
    echo "source /usr/lmod/lmod/init/bash" >> .bashenv-fms && \
    echo "module use /opt/spack-stack/spack-stack-/envs/fms-2024.01/install/modulefiles/Core" >> .bashenv-fms && \
    echo "module load stack-intel intel-oneapi-mpi" >> .bashenv-fms && \
    echo "module load stack-intel-oneapi-mpi" >> .bashenv-fms && \
    echo "DONE2" 
#
ENV SHELL=/bin/bash
