packages:
  all:
    compiler:: [intel@2021.8.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.8.0]
    target: [core2]
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.8.0
      modules:
      - impi/2021.8.0
      prefix: /opt/spack-stack/spack-stack-1.4.0/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/intel-oneapi-mpi-2021.8.0-slgdtvysm3xxsbmr54vf4arais5jfted
  bash:
    externals:
    - spec: bash@5.0.17
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.34
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.23.1
      prefix: /usr/local
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.68.0+gssapi+ldap+nghttp2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  file:
    externals:
    - spec: file@5.38
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.7.0
      prefix: /usr
  git:
    externals:
    - spec: git@2.25.1~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@2.9.2
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  mysql:
    externals:
    - spec: mysql@8.0.33
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.2p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1f
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.30.0~cpanm+open+shared+threads
      prefix: /usr
  python:
    externals:
    - spec: python@3.8.10+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.7
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.4
      prefix: /usr
  boost:
    externals:
    - spec: boost@1.78.0
      prefix: /usr
  bison:
    buildable: false
    externals:
    - spec: bison@3.5.1
      prefix: /usr
  flex:
    buildable: false
    externals:
    - spec: flex@2.6.4
      prefix: /usr




