compilers:
- compiler:
    spec: intel@=2024.2.4
    paths:
      cc: /opt/intel/oneapi/compiler/2024.2/bin/icx
      cxx: /opt/intel/oneapi/compiler/2024.2/bin/icpx
      f77: /opt/intel/oneapi/compiler/2024.2/bin/ifort
      fc: /opt/intel/oneapi/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LIBRARY_PATH: /opt/intel/oneapi/compiler/2024.2/lib
        LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/2024.2/lib
    extra_rpaths: []

