compilers:
- compiler:
    spec: intel@=2021.10.0
    paths:
      cc: /opt/intel/oneapi/compiler/2023.2.3/linux/bin/intel64/icc
      cxx: /opt/intel/oneapi/compiler/2023.2.3/linux/bin/intel64/icpc
      f77: /opt/intel/oneapi/compiler/2024.0/bin/ifort
      fc: /opt/intel/oneapi/compiler/2024.0/bin/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LIBRARY_PATH: /opt/intel/oneapi/compiler/2024.0/lib:/opt/intel/oneapi/compiler/2023.2.3/linux/compiler/lib/intel64_lin
        LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/2024.0/lib:/opt/intel/oneapi/compiler/2023.2.3/linux/compiler/lib/intel64_lin
    extra_rpaths: []

