packages:
  all:
    compiler:: [intel@2021.10.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.9.0]
    target: [core2]
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.9.0
      modules:
      - intel-oneapi-mpi/2021.9.0
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.8
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.38
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.8.2
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.23.1
      prefix: /usr/local
  python:
    externals:
    - spec: python@3.10.12+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.34.0~cpanm+open+shared+threads
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.0.2
      prefix: /usr
  git:
    externals:
    - spec: git@2.40.0+man+nls+perl+subtree~svn~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.0.2
      prefix: /usr
  curl:
    externals:
    - spec: curl@8.1.2~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.2
      prefix: /usr
  boost:
    externals:
    - spec: boost@1.78.0
      prefix: /usr
  mysql:
    externals:
    - spec: mysql@8.0.35
      prefix: /usr
  meson:
    externals:
    - spec: meson@0.61.2
      prefix: /usr
  py-scipy:
    externals:
    - spec: py-scipy@1.26.3
      prefix: /usr/local/lib/python3.10/dist-packages
  sed:
    externals:
    - spec: sed@4.8
      prefix: /usr
  awscli:
    externals:
    - spec: awscli@1.22.34
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr

