FROM noaaepic/ubuntu20.04-intel-spack-ufswm:latest
ARG CMAKE_FLAGS
ARG CMAKE_C_COMPILER
LABEL AUTHOR EPIC-AUS

# Install UFS Model 
WORKDIR /opt
RUN git clone https://github.com/ufs-community/ufs-weather-model.git ufs-weather-model 
WORKDIR /opt/ufs-weather-model
RUN git submodule update --init --recursive
ENV CMAKE_FLAGS=$CMAKE_FLAGS
ENV CMAKE_C_COMPILER=$CMAKE_C_COMPILER
RUN . /root/.bash_profile && /opt/ufs-weather-model/build.sh 
