FROM ubuntu:20.04
LABEL AUTHOR EPIC-AUS
RUN mkdir -p /opt
WORKDIR /opt
ENV DEBIAN_FRONTEND=noninteractive   
RUN apt update -y --allow-unauthenticated
RUN apt-get update -yq --allow-unauthenticated
RUN apt install -y lmod
RUN apt install -y tzdata
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime   
RUN dpkg-reconfigure --frontend noninteractive tzdata 
RUN apt -y install build-essential gfortran git openmpi-bin vim cmake python3 wget libexpat1-dev lmod
RUN apt -y install bc && apt -y install time
RUN apt-get install -yq libtiff-dev
RUN apt-get install -yq git-lfs
RUN apt install -y python3-distutils
RUN apt install -y python3-pip
RUN pip install --upgrade cmake
RUN apt install wget
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -yq m4
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
RUN apt install gdb



