# Load Intel compilers
FROM intel/hpckit:2024.2.0-1-devel-ubuntu22.04 as compilers

# Load prebuilt spack-stack with Intel runtime env
FROM noaaepic/ubuntu22.04-intel2024.2.0-1-devel-unified:v1.9.2-runtime

# Copy compilers over
RUN mv /opt/intel /opt/intel-rt
COPY --from=compilers /opt/intel /opt/intel

# Clone UFS WM Repo
WORKDIR /opt
RUN git clone -b aquaplanet --recursive https://github.com/RatkoVasic-NOAA/ufs-weather-model.git && \
    # load packages
    source /opt/spack-stack/spack-stack-1.9.2/.bashenv && \
    module unload jedi-ufs-env sp crtm && \
    module load jasper zlib libpng hdf5 netcdf-c netcdf-fortran parallelio esmf fms bacio && \
    module load crtm g2 g2tmpl ip sp w3emc gftl-shared mapl scotch py-pyyaml ecbuild && \
    # build atm executable
    mkdir -p build/atm && cd build/atm && \
    cmake .. -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_flake,FV3_GFS_v17_p8,FV3_GFS_v17_p8_rrtmgp,FV3_GFS_v15_thompson_mynn_lam3km,FV3_WoFS_v0,FV3_GFS_v17_p8_mynn,FV3_GFS_v17_p8_ugwpv1 -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release ../.. && \
    make -j 8 VERBOSE=1 && \
    cp ufs_model ../../tests-dev/fv3_atm_dyn32_intel.exe && \
    # build hafs exectuable
    cd ../ && mkdir hafs && cd hafs && \
    cmake .. -DAPP=HAFSW -DMOVING_NEST=ON -DCCPP_SUITES=FV3_HAFS_v1_thompson_nonsst,FV3_HAFS_v1_gfdlmp_tedmf,FV3_HAFS_v1_gfdlmp_tedmf_nonsst,FV3_HAFS_v1_thompson_tedmf_gfdlsf,FV3_global_nest_v1 -D32BIT=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release ../.. && \
    make -j 8 VERBOSE=1 && \
    cp ufs_model ../../tests-dev/fv3_hafsw_intel.exe
RUN mkdir -p /work && \
    mkdir -p /work2 && \
    mkdir -p /contrib && \
    mkdir -p /lustre  && \
    mkdir -p /gpfs && \
    mkdir -p /scratch3 && \
    mkdir -p /scratch4 && \
    mkdir -p /glade && \
    mkdir -p /data && \
    mkdir -p /scratch && \
    mkdir -p /lfs && \
    mkdir -p /u && \
    mkdir -p /discover && \
    mkdir -p /mnt && \
    mkdir -p /lfs1 && \
    mkdir -p /lfs2 && \
    mkdir -p /lfs3 && \
    mkdir -p /lfs4 && \
    mkdir -p /export && \
    mkdir -p /Users && \
    mkdir -p /ncrc && \
    mkdir -p /opt/ufs-weather-model/container-scripts  && \
    mkdir -p /opt/ufs-weather-model/bin

# Copy files over
COPY default_vars.sh /opt/ufs-weather-model/tests
WORKDIR /opt/ufs-weather-model/tests-dev
COPY fv3_slurm.IN_singularity test_cases/exp_conf
COPY compile_slurm.IN_singularity test_cases/exp_conf
COPY machine_singularity.config machine_config
COPY baseline_setup.yaml .
RUN chmod a+rx test_cases/exp_conf/fv3_slurm.IN_singularity test_cases/exp_conf/compile_slurm.IN_singularity && \
    chmod a+rx machine_config/machine_singularity.config baseline_setup.yaml /opt/ufs-weather-model/tests/default_vars.sh
WORKDIR /opt/ufs-weather-model/container-scripts
COPY run_container_executable.sh .
COPY build_container_executable.sh .
COPY stage-rt.sh .
RUN chmod a+rx stage-rt.sh run_container_executable.sh build_container_executable.sh

# Get container-scripts
#RUN cd /opt && rm -rf container-scripts &&  git clone https://github.com/noaa-epic/container-scripts
#RUN cd /opt/container-scripts && git remote update && git pull

# Remove compilers and set runtime env
RUN rm -rf /opt/intel && \
    mv /opt/intel-rt /opt/intel
